language: python
python:
  - "2.7"
#  - "3.5" # temporarily remove 3.5 because we use ConfigParser!!

services:
  - mongodb

install:
    - pip install -r requirements.txt
    - cd ..
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - export PATH=$(pwd)/bin:$PATH
    - cd ../catalog
    - make

script: 
    - make test