language: python
python:
    - '2.7'
services:
    - mongodb
install:
    - pip install -r requirements.txt
    - cd ..
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - export PATH=$(pwd)/bin:$PATH
    - cd ../catalog
    - make
script:
    - cp -n test/test.cfg.example test/test.cfg
    - sed -i 's/^nms-admin-psswd.*/nms-admin-psswd = '$NMS_ADMIN_PWD'/' test/test.cfg.example
    - make test
env:
  global:
    secure: 3rav9OwWd1KLca8QDfqyefulMxtG3rJWOJPuJc3cOuJzKMldZeTXU6366mgLbViCojyJ8klhGFWS89dERn5pXJukS3t8gEVyljJ8klAnwVBHI3TaUXDR1F3YJRNQfc0QPOAuJuVZNdLz4K9ERwsf7E04qaCdRW/yZ5cp6HW6fI55eyDAqK5G2LVDH0UBqQqj/FacXSz9pYhm3mWryD0gj0nkumD0y78YXACSrPAKM3UnX6fWQNrLVrFD4S2iR3HhRm4DxwsD4NlhaKZ0ShWjytETtwnx4xw+CawmUFfHOC844Xz8P6PdTZh1PBG1FEq97Ut1Eq/+3aYRn2OScchSKYVf538Z3UrjVQJOq9rBg6aps45icME9RfCQYXSmv6PHWqz4g2Ofcq7rdUjAAZC3jo/xht/DZynxZLqdQkfr2f3a2BZjqJiaF/uDPuOgxIt6ugYa+IPztIWNT9ICauw5IN0iXzhOv7TlaAkHKoQ1124DdpTylvJBi6K1idZUMXuMXtKdDMzdGI3c0JzNqF7i0RTrKSvycv7VS2NQk2URFAxTf6TQKiLXMb/KIqghnx2SBq3hP/mgsZzpkpVyGQpMm1D+/J+KJzvfjqc+ENja3333K9poEv2vn4I35ZQEAEKo8r5Z7ywo3aGc7a75Mvx9TSBwWGQAi8OZEKlZdb7EnBs=
