language: python
python:
    - '2.7'
services:
    - mongodb
install:
    - pip install -r requirements.txt
    - cd ..
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - export PATH=$(pwd)/bin:$PATH
    - cd ../catalog
    - make
script:
    - cp -n test/test.cfg.example test/test.cfg
    - sed -i 's/^nms-admin-psswd.*/nms-admin-psswd = '$NMS_ADMIN_PWD'/' test/test.cfg.example
    - cat test/test.cfg
    - make test
env:
  global:
    secure: "NU6Rx2OuOxmLnPvkAP5chXA3HXtRka64gJSpd+V3wtA9mSa7WYWHadhvV0ufBHsC43g9s0pmYLwJylM16sYpyGJDA7KDfaAap5WVj11J3aWDvCnJYDTJOYPHFkdMq8Er3pZrLXej+aSnesWvNOwEVmoJzgfr98dI2JssqELrxeXVG0zcjJ9CC5g0vPjzocsF9xIHpr2CUKhP47WchC9I6RtGv0hoPAWwmPNKv5uc+/VdPxZ68X4WLH5hiFK/CbItVfNE/6kocJW2mryUHr2p98AUndqjd+tbiaDcdmsxqP6wXjGh4pZIcBVqGtm0iwo8R3N0wKqla1XKSVXAf0JsH3QpTi2FrPW1ICW4JDG5qmT+q09yQGNq/pml8NeKHzTELfUgsZLBBdXsTFHLkqsvm0N7I+hAGR+YqMU2ZYbAWBG3gjg5NsLBpxVocRNWMJ+myxd8VeHhYsWR7CmAG15epNM4B2d+LaFv+ngIgjnVmD0f4gjXIk6EukLWULzmGEWYgLh7p9zPXftsSHySyPzBo2uEJokKqrBNenvesSEHqoB/ZutofN3KxahLIJmhhZtp5UJZaSb1znU3+nG6fgCtJkIUrM4cRY8TXz4sdnjNZDUh4zxD8l5nQ8LvDxkSjeZT3PaTWs6ARzlndiAzYRsDij0ES338FDg9hpo3VFSW2qg="
