sudo: required
language: python
python:
    - '2.7'
services:
    - docker

before_install:
    #- docker run -d -p 5000:5000 --name registry registry:2
    - docker run -p 27017:27017 --name mongo2.7 -d mongo:2.7
    - sleep 3
    - mongo --eval "printjson(db.serverStatus())"

install:
    - pip install -r travis_requirements.txt
    - pip install python-coveralls
    - pip install coverage
    - cd ..
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - git checkout 9b628a9
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../catalog
    - make

script:
    - cp -n test/test.cfg.example test/test.cfg
    - sed -i 's/^nms-admin-toke.*/nms-admin-token = '$NMS_ADMIN_TOKEN'/' test/test.cfg
    - make test

after_success:
  - mv test/.coverage .
  - coveralls

env:
  global:
    - secure: "1ZtZoWNjnZzFATNu6ng71syl8XYkKpETITyYmMjz0S8mTOKunKjtporXkUuNai3AOTlnIvaS9GwQ8XBtrP1KJEi4k1KXzcS+EmtPAXfFsIVFvdfLQPHmENUEhSV2i7F8bx+tBppa/90lPwLuFwjMjUQP6xJU3zVnQXvfPRUgWv7nzUifrrO59NwnzrBcLQ8c67pKbMqIvMR3ZKNNOUv067lyXiUi58UZqKoSzOJI5oPDy/2JnTzLfpPY49w1Z7tcsyssUJOHCD8wKpGoVOBboYcdXilVdRkM2IJuD8qzKJCyBPkVwD8FuA/OVxWfCanmrboobfVKIIayna6K1RwXP8B61yJV9V/HNnn6VyWdiD8jk9JSBGY8FecNQLc8r02TlJKugpEcw/iujW1b8ZMqxfmZrU2s1djbY80bnikBgNW1T5QzGniQy6SwmiBL5+HvZMXS425gIxDhcnH2heHGGkpTW/JVchtIJgiM4JQoLUup9z5oC0d4pqiMlgbiarkDAE8S9AYriEw8bvnzKJnRNb0ElZBqbUXVuFpIXTVv6kxlpJh28GfEWk7WZ7KOBkSYHB5TfkxIgrh2QyqAniCSVHBZ7i5gimd3gCUbeuxe3zvONLJTug63/QwlqEbzGFh6+A/YC4Eada1Li+V1mneA4KG5IKOl0BeOUe1iqZAZFm8="
    - MONGODB_VERSION=2.7
